spring:
  application:
    name: slace
  profiles:
    active: production
---
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://heroku_p1xd1sjm:j762tql5ksq8hf12b9ilmjhok4@ds163561.mlab.com:63561/heroku_p1xd1sjm
storage:
  location: ${user.home}/tmp
---
spring:
  profiles: local
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/slace
storage:
  location: E:\proj\slace\files\
server:
    port: 8081
---
