spring:
  profiles: dev

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/slace

jwt.secret: testesttes

storage:
  location: E:\proj\slace\files\

sms:
  twilio:
    account:
      sid: asdas
      token: dsadsa
    number: dsadsadsa

server:
  port: 8081