spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}

jwt.secret: ${TOKEN_SECRET}

storage:
  location: ${STORAGE_LOCATION}

sms:
  twilio:
    account:
      sid: ${TWILIO_SID}
      token: ${TWILIO_TOKEN}
    number: ${TWILIO_NUMBER}
