spring:
  application:
    name: slace
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**

server:
  error:
    path: /500

api.prefix: /api

jwt:
  expiration: 10080000
  rememberMeExpiration: 44640000
