spring:
  application:
    name: slace
  profiles:
    active: dev, embedded
  mvc:
    static-path-pattern: /**
  session:
    store-type: redis

server:
  error:
    path: /500

api.prefix: /api

jwt:
  expiration: 10080000
  rememberMeExpiration: 44640000
