spring:
  application:
    name: slace
  profiles:
    active: local
jwt:
  expiration: 10080000
  rememberMeExpiration: 44640000
---
spring:
  profiles: production

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

jwt.secret: ${TOKEN_SECRET}

storage:
  location: /tmp
---
spring:
  profiles: local

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/slace

jwt:
  secret: testesttes

storage:
  location: E:\proj\slace\files\

server:
  port: 8081
---