spring:
  profiles: dev
  redis:
    port: 6379
    password:
    host: localhost

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/slace

jwt.secret: testesttes

storage:
  location: E:\proj\slace\files\

sms:
  twilio:
    account:
      sid: asdas
      token: dsadsa
    number: dsadsadsa

server:
  port: 8081